# documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel

sudo: true
dist: trusty
cache: packages
warnings_are_errors: true

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

#r_build_args: "--no-build-vignettes"
#r_check_args: "--no-build-vignettes --as-cran"

r_binary_packages:
  - stringi
  - magrittr
  - curl
  - jsonlite
  - Rcpp
  - RcppEigen
  - openssl
  - utf8
  - gss
  - httpuv
  - markdown
  - sem
  - readxl
  - openxlsx
  - pander
  - git2r

r_packages:
  - rlang
  - bindrcpp
  - purrr
  - tidyr
  - dplyr

r_github_packages:
  - jimhester/lintr
  - r-lib/covr

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls(type = "all")'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
